### ISSUE TITLE
本地色图发送失败

### ISSUE THREAD

**Issue by Hanx152** [ayanamiblhx/nonebot_plugin_setu#10]
他文件夹里下了200多张，但是我关闭在线发图之后再发涩图，他说没有涩图啦，也没有报错啥的

**Comment by ayanamiblhx** [comment]
> 他文件夹里下了200多张，但是我关闭在线发图之后再发涩图，他说没有涩图啦，也没有报错啥的

涩涩图片和普通图片存放在不同的目录，下载涩涩图片请使用下载色图，否则请使用下载涩图

**Comment by ayanamiblhx** [comment]
> 他文件夹里下了200多张，但是我关闭在线发图之后再发涩图，他说没有涩图啦，也没有报错啥的
![image](https://user-images.githubusercontent.com/63199041/163698221-4bfce020-7edb-44c8-ab75-f464740d3291.png)

**Comment by Hanx152** [comment]
之前我打的就是下载色图，之前就发不出来，但现在重现下载色图就又好了，总之谢谢大佬
