### ISSUE TITLE
群cd和关闭功能失效

### ISSUE THREAD

**Issue by beiweixiaotian** [ayanamiblhx/nonebot_plugin_setu#11]
![IMG_20220422_010042.jpg](https://user-images.githubusercontent.com/58933417/164512864-041901bd-97c2-4fb0-a525-717c709aca6f.jpg)
![IMG_20220422_010335.jpg](https://user-images.githubusercontent.com/58933417/164513303-4fa7127a-8f67-46e6-b3b6-e1fec6c9f6c7.jpg)

**Comment by ayanamiblhx** [comment]
> ![IMG_20220422_010042.jpg](https://user-images.githubusercontent.com/58933417/164512864-041901bd-97c2-4fb0-a525-717c709aca6f.jpg)![IMG_20220422_010212.jpg](https://user-images.githubusercontent.com/58933417/164513141-b93c7695-2d71-47aa-b978-e0a69b9b3dbf.jpg)

cd对超级用户无效

**Comment by beiweixiaotian** [comment]
超级用户是指管理员吗

**Comment by ayanamiblhx** [comment]
> 超级用户是指管理员吗

超级用户是你在setu_config.json里填的superusers

**Comment by beiweixiaotian** [comment]
> > ![IMG_20220422_010042.jpg](https://user-images.githubusercontent.com/58933417/164512864-041901bd-97c2-4fb0-a525-717c709aca6f.jpg)![IMG_20220422_010212.jpg](https://user-images.githubusercontent.com/58933417/164513141-b93c7695-2d71-47aa-b978-e0a69b9b3dbf.jpg)
> 
> cd对超级用户无效

是指管理员和群主吗

**Comment by beiweixiaotian** [comment]
> > 超级用户是指管理员吗
> 
> 超级用户是你在setu_config.json里填的superusers
就设置了一个，就是图上那个群主

**Comment by ayanamiblhx** [comment]
> > > 超级用户是指管理员吗
> > 
> > 超级用户是你在setu_config.json里填的superusers
> 就设置了一个，就是图上那个群主

cd一直不起作用?

**Comment by beiweixiaotian** [comment]
> > > > 超级用户是指管理员吗
> > > 
> > > 超级用户是你在setu_config.json里填的superusers
> > 就设置了一个，就是图上那个群主
> 
> cd一直不起作用?

![IMG_20220422_011826.jpg](https://user-images.githubusercontent.com/58933417/164515631-6d8c0269-2492-45e5-8d52-758b8a53c753.jpg)

**Comment by beiweixiaotian** [comment]
> > > > 超级用户是指管理员吗
> > > 
> > > 超级用户是你在setu_config.json里填的superusers
> > 就设置了一个，就是图上那个群主
> 
> cd一直不起作用?
关闭功能不起作用，我刚才看到了cd的优先级，这么设置是不是不太合理？

**Comment by ayanamiblhx** [comment]
> > > > > 超级用户是指管理员吗
> > > > 
> > > > 超级用户是你在setu_config.json里填的superusers
> > > 就设置了一个，就是图上那个群主
> > 
> > cd一直不起作用?
> 
> ![IMG_20220422_011826.jpg](https://user-images.githubusercontent.com/58933417/164515631-6d8c0269-2492-45e5-8d52-758b8a53c753.jpg)

是否单独为这个账号设置了cd

**Comment by beiweixiaotian** [comment]
> > > > > > 超级用户是指管理员吗
> > > > > 
> > > > > 超级用户是你在setu_config.json里填的superusers
> > > > 就设置了一个，就是图上那个群主
> > > 
> > > cd一直不起作用?
> > 
> > ![IMG_20220422_011826.jpg](https://user-images.githubusercontent.com/58933417/164515631-6d8c0269-2492-45e5-8d52-758b8a53c753.jpg)
> 
> 是否单独为这个账号设置了cd

是的，设置了cd

**Comment by beiweixiaotian** [comment]
> > > > > > > 超级用户是指管理员吗
> > > > > > 
> > > > > > 超级用户是你在setu_config.json里填的superusers
> > > > > 就设置了一个，就是图上那个群主
> > > > 
> > > > cd一直不起作用?
> > > 
> > > ![IMG_20220422_011826.jpg](https://user-images.githubusercontent.com/58933417/164515631-6d8c0269-2492-45e5-8d52-758b8a53c753.jpg)
> > 
> > 是否单独为这个账号设置了cd
> 
> 是的，设置了cd

你的意思是个人的cd优先级>群cd>功能开关？

**Comment by beiweixiaotian** [comment]
> > > > > > > > 超级用户是指管理员吗
> > > > > > > 
> > > > > > > 超级用户是你在setu_config.json里填的superusers
> > > > > > 就设置了一个，就是图上那个群主
> > > > > 
> > > > > cd一直不起作用?
> > > > 
> > > > ![IMG_20220422_011826.jpg](https://user-images.githubusercontent.com/58933417/164515631-6d8c0269-2492-45e5-8d52-758b8a53c753.jpg)
> > > 
> > > 是否单独为这个账号设置了cd
> > 
> > 是的，设置了cd
> 
> 用户cd和群cd同时存在时以用户cd为准，另外关闭涩涩指的是关闭r18

啊，懂了
