### ISSUE TITLE
请求新增关闭发送链接设置

### ISSUE THREAD

**Issue by starxjys** [ayanamiblhx/nonebot_plugin_setu#13]
链接发多了会被tx误判为《涉嫌诈骗》。。

**Comment by ayanamiblhx** [comment]
> 链接发多了会被tx误判为《涉嫌诈骗》。。

你确定不是其它原因或者是被举报了

**Comment by starxjys** [comment]
> > 链接发多了会被tx误判为《涉嫌诈骗》。。
> 
> 你确定不是其它原因或者是被举报了

目前找不到其他理由，两次tx的理由都是涉嫌诈骗，但机器人确实只有发涩图。另外机器人只在小群内使用，没有内鬼（雾

**Comment by ayanamiblhx** [comment]
> > > 链接发多了会被tx误判为《涉嫌诈骗》。。
> > 
> > 你确定不是其它原因或者是被举报了
> 
> 目前找不到其他理由，两次tx的理由都是涉嫌诈骗，但机器人确实只有发涩图。另外机器人只在小群内使用，没有内鬼（雾

可以手动改源码，将发送链接那部分删除
