### ISSUE TITLE
机器人被风控 但是过一会又能使用

### ISSUE THREAD

**Issue by Arturia169** [ayanamiblhx/nonebot_plugin_setu#14]
![QQ截图20220519124241](https://user-images.githubusercontent.com/69199123/169206875-3e4ba7bc-7d58-4739-ae39-ba7b83f1f048.png)

**Comment by ayanamiblhx** [comment]
> ![QQ截图20220519124241](https://user-images.githubusercontent.com/69199123/169206875-3e4ba7bc-7d58-4739-ae39-ba7b83f1f048.png)
> 

偶尔出问题的话可能是网络波动

**Comment by Arturia169** [comment]
这样啊 那就不管他了能用就完事了

**Comment by Arturia169** [comment]
这样啊 那就不管他了能用就完事了
