### ISSUE TITLE
tag混乱

### ISSUE THREAD

**Issue by broken2211** [ayanamiblhx/nonebot_plugin_setu#15]
我不知道为什么tag不是显示没有，就是乱发图。有些是标题上有tag才发对
![H WK AHL WE28NR79VE78(0](https://user-images.githubusercontent.com/51013794/169634466-d772cfa2-7311-436f-b606-3fca0b39adab.png)
的

**Comment by broken2211** [comment]
大佬，这是为什么

**Comment by ayanamiblhx** [comment]
> 大佬，这是为什么

图源的问题，图源里面有多张图片，记录的tag不止一个

**Comment by broken2211** [comment]
没有，他就一张图，所以我才纳闷

**Comment by ayanamiblhx** [comment]
> 没有，他就一张图，所以我才纳闷

p站图源不止一张图，导致记录的tag不止一个

**Comment by broken2211** [comment]
![0BY02A9X@)0D7F7E2SMJ3TW](https://user-images.githubusercontent.com/51013794/169634811-588a3d4b-2381-42fe-823c-906f50edbbb7.png)

**Comment by ayanamiblhx** [comment]
> ![0BY02A9X@)0D7F7E2SMJ3TW](https://user-images.githubusercontent.com/51013794/169634811-588a3d4b-2381-42fe-823c-906f50edbbb7.png)
> 

调一下api看看，用tag搜索不知火舞

**Comment by broken2211** [comment]
抱歉，找到问题了，是另一个图片插件出现问题。不是这个，万分抱歉
