### ISSUE TITLE
分批下载中单批量数目的倍数导致的API错误及批下载数目太大了导致的API错误

### ISSUE THREAD

**Issue by marko1616** [ayanamiblhx/nonebot_plugin_setu#19]
在批量下载数目为单次下载数目的倍数时会导致变量remain == 0(getPic.py)进而导致API请求错误

**Comment by ayanamiblhx** [comment]
> 在批量下载数目为单次下载数目的倍数时会导致变量remain == 0(getPic.py)进而导致API请求错误

刚刚查看了一下，LOL icon现在改规则了，一次最大请求图片数量变成了20，正在修改
