### ISSUE TITLE
获取信息失败

### ISSUE THREAD

**Issue by Kirikokora** [ayanamiblhx/nonebot_plugin_setu#2]
![image](https://user-images.githubusercontent.com/88840162/129449548-bc4558a8-24d2-47f3-bd98-99901e1b6062.png)

**Comment by ayanamiblhx** [comment]
看看.env配置文件？

**Comment by Kirikokora** [comment]
这几天上课没时间动
等周末聊





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ayanamiblhx/nonebot_plugin_setu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 上午9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ayanamiblhx/nonebot_plugin_setu] 获取信息失败 (#2)





 
看看.env配置文件？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kirikokora** [comment]
> 看看.env配置文件？

![image](https://user-images.githubusercontent.com/88840162/129928543-34ba87e2-3992-47a6-8b9f-787e2eb5238e.png)
现在是这个问题
之前那个看错了

**Comment by ayanamiblhx** [comment]
没挂代理

**Comment by Kirikokora** [comment]
> 看看.env配置文件？



> 没挂代理

一定要代理吗

**Comment by ayanamiblhx** [comment]
是的

**Comment by Kirikokora** [comment]
> 是的

那个cd后面要带那个秒字吗

**Comment by ayanamiblhx** [comment]
不加

**Comment by Kirikokora** [comment]
> 是的

这是我代理问题还是怎么了

**Comment by ayanamiblhx** [comment]
应该是你代理问题

**Comment by urla111** [comment]
请问我挂了代理也是这样是为什么？
对网站有什么限制吗

**Comment by ayanamiblhx** [comment]
> 请问我挂了代理也是这样是为什么？
> 对网站有什么限制吗

看看.env配置文件？

**Comment by urla111** [comment]
![K4}`IZ{)DR6$WJVA`_BZR](https://user-images.githubusercontent.com/74201689/130069591-9f5e8fd8-cd92-4202-bed7-086df96aeff4.png)
是不是我写的网站有问题。。。

**Comment by ayanamiblhx** [comment]
> ![K4}IZ{)DR6$WJVA_BZR](https://user-images.githubusercontent.com/74201689/130069591-9f5e8fd8-cd92-4202-bed7-086df96aeff4.png)
> 是不是我写的网站有问题。。。

配置文件，报错信息都发一下

**Comment by urla111** [comment]
![Uploading XE4GSM7J]KU~8R{1QVW50{K.png…]()
![H6350NGDF8}TG%A1Y3((Z}L](https://user-images.githubusercontent.com/74201689/130070001-9acecceb-b5b0-4b21-916c-b4242dd1d033.png)

**Comment by urla111** [comment]
![H6350NGDF8}TG%A1Y3((Z}L](https://user-images.githubusercontent.com/74201689/130070051-9507bc79-e91e-4257-95fd-813bbc5b674e.png)
![XE4GSM7J KU~8R{1QVW50{K](https://user-images.githubusercontent.com/74201689/130070074-cf240dd0-6fc7-4ce1-864c-eb4e00beb364.png)

**Comment by ayanamiblhx** [comment]
你localproxy里面填的啥？订阅链接？

**Comment by ayanamiblhx** [comment]
> ![K4}IZ{)DR6$WJVA_BZR](https://user-images.githubusercontent.com/74201689/130069591-9f5e8fd8-cd92-4202-bed7-086df96aeff4.png)
> 是不是我写的网站有问题。。。

你localproxy里面填的啥？订阅链接？

**Comment by urla111** [comment]
一个网站。。
这个里面应该填啥，我不大懂

**Comment by ayanamiblhx** [comment]
> 一个网站。。
> 这个里面应该填啥，我不大懂

先去学一下怎么挂代理

**Comment by urla111** [comment]
![image](https://user-images.githubusercontent.com/74201689/130221906-b29cf4ad-71f6-435b-8e94-e805394eaaea.png)

**Comment by urla111** [comment]
![image](https://user-images.githubusercontent.com/74201689/130221985-5cf289c2-8e41-42b0-ade1-1d79cebf6b67.png)
这是为啥

**Comment by ayanamiblhx** [comment]
> ![image](https://user-images.githubusercontent.com/74201689/130221985-5cf289c2-8e41-42b0-ade1-1d79cebf6b67.png)
> 这是为啥

你代理问题

**Comment by MasterYuan418** [comment]
@urla111 我怎么感觉你这个问题也类似于
Duplicate of #3 啊，也许你应该考虑一下你的魔法链接是否正确。
同时，我访问了一下acgrr.cyou，感觉不像是魔法链接？
