### ISSUE TITLE
bot一直被风控 是网络问题吗

### ISSUE THREAD

**Issue by lzsyxy** [ayanamiblhx/nonebot_plugin_setu#21]
可能是我魔法配置错了 但是关闭魔法后也一直被无脑风控 没有不被风控过😰

**Comment by ayanamiblhx** [comment]
> 可能是我魔法配置错了 但是关闭魔法后也一直被无脑风控 没有不被风控过😰

看看gocq和nonebot日志

**Comment by lzsyxy** [comment]
搜索tag输入一些不存在的tag也回复被风控

**Comment by ayanamiblhx** [comment]
> 搜索tag输入一些不存在的tag也回复被风控

看看日志

**Comment by lzsyxy** [comment]
这应该是nonebot的日志？
11-01 12:38:45 [SUCCESS] nonebot | OneBot V11 3635626104 | [message.group.normal]: Message 1469534191 from 1092412751@[ 群:429277147] "涩图"
11-01 12:38:45 [DEBUG] nonebot | Checking for matchers in priority 1...
11-01 12:38:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_setu)
11-01 12:38:45 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_setu)
11-01 12:38:45 [DEBUG] nonebot | Running handler Dependent(call=_)
11-01 12:38:45 [ERROR] nonebot_plugin_setu |
11-01 12:38:45 [ERROR] nonebot_plugin_setu | 机器人被风控了
11-01 12:38:45 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
11-01 12:38:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_setu) running complete
11-01 12:38:45 [DEBUG] nonebot | Stop event propagation
这是gocq的日志
[2022-11-01 12:37:32] [WARNING]: 监听反向WS Universal时出现错误: read tcp 127.0.0.1:1921->127.0.0.1:53245: wsarecv: An existing connection was forcibly closed by the remote host. 
[2022-11-01 12:38:33] [WARNING]: Protocol -> device lock is disable. http api may fail.

**Comment by ayanamiblhx** [comment]
> 这应该是nonebot的日志？
> 11-01 12:38:45 [SUCCESS] nonebot | OneBot V11 3635626104 | [message.group.normal]: Message 1469534191 from 1092412751@[ 群:429277147] "涩图"
> 11-01 12:38:45 [DEBUG] nonebot | Checking for matchers in priority 1...
> 11-01 12:38:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_setu)
> 11-01 12:38:45 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_setu)
> 11-01 12:38:45 [DEBUG] nonebot | Running handler Dependent(call=_)
> 11-01 12:38:45 [ERROR] nonebot_plugin_setu |
> 11-01 12:38:45 [ERROR] nonebot_plugin_setu | 机器人被风控了
> 11-01 12:38:45 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
> 11-01 12:38:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_setu) running complete
> 11-01 12:38:45 [DEBUG] nonebot | Stop event propagation
> 这是gocq的日志
> [2022-11-01 12:37:32] [WARNING]: 监听反向WS Universal时出现错误: read tcp 127.0.0.1:1921->127.0.0.1:53245: wsarecv: An existing connection was forcibly closed by the remote host. 
> [2022-11-01 12:38:33] [WARNING]: Protocol -> device lock is disable. http api may fail. 

gocq日志发全了吗，怎么没看见12:38:45的

**Comment by ayanamiblhx** [comment]
> > 
> 
> 我这边确实看不到12:38:45的日志信息 也许我应该重新安装插件试试？

你重新发一下涩图命令看看gocq日志，发消息必然会有日志的

**Comment by lzsyxy** [comment]
> > > 
> > 
> > 
> > 我这边确实看不到12:38:45的日志信息 也许我应该重新安装插件试试？
> 
> 你重新发一下涩图命令看看gocq日志，发消息必然会有日志的

试了一下 不止这个命令 其他命令也看不到日志 倒是在昨天晚上的日志看到这一条
 [FATAL]: open image cache failed: 文件被其他进程占用 
不知道有没有关系

**Comment by lzsyxy** [comment]
我这边刚发了涩图命令突然出图了 但是还是看不到日志

**Comment by lzsyxy** [comment]
往群里发有时候蹦一条这个
[WARNING]: 群消息发送失败: 账号可能被风控. 
但是
11-01 16:38:41 [ERROR] nonebot_plugin_setu | 机器人被风控了
11-01 16:38:41 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
11-01 16:38:42 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_setu) running complete
11-01 16:38:42 [DEBUG] nonebot | Stop event propagation
风控之后又自动call了一次发出来了

**Comment by lzsyxy** [comment]
突然正常了 不好意思麻烦您这么久 但就是不知道能正常多久 感谢您的耐心

**Comment by ayanamiblhx** [comment]
> 突然正常了 不好意思麻烦您这么久 但就是不知道能正常多久 感谢您的耐心

gocq显示风控那就是真的风控了，没法，建议多挂几天

**Comment by lzsyxy** [comment]
插件不配置魔法的时候后台挂魔法好像就会无脑风控诶 是要重新配置魔法吗

**Comment by ayanamiblhx** [comment]
> 插件不配置魔法的时候后台挂魔法好像就会无脑风控诶 是要重新配置魔法吗

看看日志

**Comment by ayanamiblhx** [comment]
> 插件不配置魔法的时候后台挂魔法好像就会无脑风控诶 是要重新配置魔法吗

如果不会配置魔法就把它关了，不然就没法获取图片

**Comment by lzsyxy** [comment]
gocq有被风控日志都是正常被风控的 挂魔法被无脑风控的时候gocq日志没有信息 而且我发送关闭涩涩命令后也是一样的情况

**Comment by ayanamiblhx** [comment]
> gocq有被风控日志都是正常被风控的 挂魔法被无脑风控的时候gocq日志没有信息 而且我发送关闭涩涩命令后也是一样的情况

关闭魔法请使用命令`关闭魔法`

**Comment by lzsyxy** [comment]
不好意思说错了 我确实是发送的关闭魔法

**Comment by ayanamiblhx** [comment]
> 不好意思说错了 我确实是发送的关闭魔法

请发送实时gocq和nonebot日志截图

**Comment by lzsyxy** [comment]
> > 不好意思说错了 我确实是发送的关闭魔法
> 
> 请发送实时gocq和nonebot日志截图

![image](https://user-images.githubusercontent.com/96862482/199464458-89a01fca-fa3c-40e3-87c1-358b051b3104.png)
这是有时候被正常风控的gocq日志 其他时候gocq确实都没有新日志信息（还是说在bot运行的时候日志不会更新？）
![image](https://user-images.githubusercontent.com/96862482/199463686-9aff080d-b859-49a8-91da-df39239c228d.png)
这是分别在有魔法和没魔法被风控和正常发图的nonebot日志

**Comment by ayanamiblhx** [comment]
> > > 不好意思说错了 我确实是发送的关闭魔法
> > 
> > 请发送实时gocq和nonebot日志截图
> 
> ![image](https://user-images.githubusercontent.com/96862482/199464458-89a01fca-fa3c-40e3-87c1-358b051b3104.png)
> 这是有时候被正常风控的gocq日志 其他时候gocq确实都没有新日志信息（还是说在bot运行的时候日志不会更新？）
> ![image](https://user-images.githubusercontent.com/96862482/199463686-9aff080d-b859-49a8-91da-df39239c228d.png)
> 这是分别在有魔法和没魔法被风控和正常发图的nonebot日志 

请把nonebot和gocq在前台运行，然后发送相关命令并截图

**Comment by lzsyxy** [comment]
> > > > 不好意思说错了 我确实是发送的关闭魔法
> > > 
> > > 
> > > 请发送实时gocq和nonebot日志截图
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/96862482/199464458-89a01fca-fa3c-40e3-87c1-358b051b3104.png)
> > 这是有时候被正常风控的gocq日志 其他时候gocq确实都没有新日志信息（还是说在bot运行的时候日志不会更新？）
> > ![image](https://user-images.githubusercontent.com/96862482/199463686-9aff080d-b859-49a8-91da-df39239c228d.png)
> > 这是分别在有魔法和没魔法被风控和正常发图的nonebot日志
> 
> 请把nonebot和gocq在前台运行，然后发送相关命令并截图

对不起！请问怎么在前台运行 暂时没找到教程 小的是纯小白

**Comment by ayanamiblhx** [comment]
> > > > > 不好意思说错了 我确实是发送的关闭魔法
> > > > 
> > > > 
> > > > 请发送实时gocq和nonebot日志截图
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/96862482/199464458-89a01fca-fa3c-40e3-87c1-358b051b3104.png)
> > > 这是有时候被正常风控的gocq日志 其他时候gocq确实都没有新日志信息（还是说在bot运行的时候日志不会更新？）
> > > ![image](https://user-images.githubusercontent.com/96862482/199463686-9aff080d-b859-49a8-91da-df39239c228d.png)
> > > 这是分别在有魔法和没魔法被风控和正常发图的nonebot日志
> > 
> > 请把nonebot和gocq在前台运行，然后发送相关命令并截图
> 
> 对不起！请问怎么在前台运行 暂时没找到教程 小的是纯小白

就正常运行，然后把运行窗口截图

**Comment by lzsyxy** [comment]
> > > > > > 不好意思说错了 我确实是发送的关闭魔法
> > > > > 
> > > > > 
> > > > > 请发送实时gocq和nonebot日志截图
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/96862482/199464458-89a01fca-fa3c-40e3-87c1-358b051b3104.png)
> > > > 这是有时候被正常风控的gocq日志 其他时候gocq确实都没有新日志信息（还是说在bot运行的时候日志不会更新？）
> > > > ![image](https://user-images.githubusercontent.com/96862482/199463686-9aff080d-b859-49a8-91da-df39239c228d.png)
> > > > 这是分别在有魔法和没魔法被风控和正常发图的nonebot日志
> > > 
> > > 
> > > 请把nonebot和gocq在前台运行，然后发送相关命令并截图
> > 
> > 
> > 对不起！请问怎么在前台运行 暂时没找到教程 小的是纯小白
> 
> 就正常运行，然后把运行窗口截图

但是我平时运行就是这样的😢 我就是在bot目录打开powershell nb run 然后打开gocq.bat就能正常运行了😢

**Comment by ayanamiblhx** [comment]
> > > > > > > 不好意思说错了 我确实是发送的关闭魔法
> > > > > > 
> > > > > > 
> > > > > > 请发送实时gocq和nonebot日志截图
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/96862482/199464458-89a01fca-fa3c-40e3-87c1-358b051b3104.png)
> > > > > 这是有时候被正常风控的gocq日志 其他时候gocq确实都没有新日志信息（还是说在bot运行的时候日志不会更新？）
> > > > > ![image](https://user-images.githubusercontent.com/96862482/199463686-9aff080d-b859-49a8-91da-df39239c228d.png)
> > > > > 这是分别在有魔法和没魔法被风控和正常发图的nonebot日志
> > > > 
> > > > 
> > > > 请把nonebot和gocq在前台运行，然后发送相关命令并截图
> > > 
> > > 
> > > 对不起！请问怎么在前台运行 暂时没找到教程 小的是纯小白
> > 
> > 就正常运行，然后把运行窗口截图
> 
> 但是我平时运行就是这样的😢 我就是在bot目录打开powershell nb run 然后打开gocq.bat就能正常运行了😢

就截正常运行的窗口上面的日志图

**Comment by lzsyxy** [comment]
抱歉再次没有及时回复 下面是截图 请看
![U5TRDQUSQ 2P6X{XPBR1_0P](https://user-images.githubusercontent.com/96862482/199642151-acb1b280-9055-443e-838c-d83fe8ef4844.png)
第一次发涩图命令后台未挂魔法 后两次都是在挂了魔法的情况下发送涩图命令 插件setting里的代理未配置

**Comment by ayanamiblhx** [comment]
> 抱歉再次没有及时回复 下面是截图 请看
> ![U5TRDQUSQ 2P6X{XPBR1_0P](https://user-images.githubusercontent.com/96862482/199642151-acb1b280-9055-443e-838c-d83fe8ef4844.png)
> 第一次发涩图命令后台未挂魔法 后两次都是在挂了魔法的情况下发送涩图命令 插件setting里的代理未配置

如果没有配置代理请把魔法关闭，否则无法获取图片

**Comment by lzsyxy** [comment]
谢谢您的解答
