### ISSUE TITLE
无法私聊发送涩图

### ISSUE THREAD

**Issue by NegativeFactor** [ayanamiblhx/nonebot_plugin_setu#22]
已加为好友，用户设置cd数为0，开启私聊涩涩，无论是机器人主人还是其他用户均无法通过私聊收到“涩图”指令的色图
群聊消息正常，其他功能群聊以及私聊时可用
nonebot和go-cqhttp均提示发送成功，但用户未收到聊天消息
以下是记录以及配置文件
![QQ图片20221211233728](https://user-images.githubusercontent.com/89331923/206913122-c1e84c85-119e-4e42-b8e4-f8a951288ba7.png)
![QQ图片20221211233744](https://user-images.githubusercontent.com/89331923/206913126-af08aa1c-ba08-4a28-8810-863e357f0e71.png)
![QQ图片20221211233747](https://user-images.githubusercontent.com/89331923/206913130-8d311097-2502-4271-bda6-f9b0b4ff8c30.png)
![QQ图片20221211233835](https://user-images.githubusercontent.com/89331923/206913132-41286fae-53a3-4c8d-b125-94af84a56d24.png)

**Comment by ayanamiblhx** [comment]
> 请问这个目前有解决方法吗，没有提示任何错误

最近暂时没时间看，请稍等几天

**Comment by NegativeFactor** [comment]
> 

行，麻烦您了

**Comment by ayanamiblhx** [comment]
> 已加为好友，用户设置cd数为0，开启私聊涩涩，无论是机器人主人还是其他用户均无法通过私聊收到“涩图”指令的色图 群聊消息正常，其他功能群聊以及私聊时可用 nonebot和go-cqhttp均提示发送成功，但用户未收到聊天消息 以下是记录以及配置文件 ![QQ图片20221211233728](https://user-images.githubusercontent.com/89331923/206913122-c1e84c85-119e-4e42-b8e4-f8a951288ba7.png) ![QQ图片20221211233744](https://user-images.githubusercontent.com/89331923/206913126-af08aa1c-ba08-4a28-8810-863e357f0e71.png) ![QQ图片20221211233747](https://user-images.githubusercontent.com/89331923/206913130-8d311097-2502-4271-bda6-f9b0b4ff8c30.png) ![QQ图片20221211233835](https://user-images.githubusercontent.com/89331923/206913132-41286fae-53a3-4c8d-b125-94af84a56d24.png)

已修复，请更新至1.1.7
