### ISSUE TITLE
能否增加command start

### ISSUE THREAD

**Issue by QLozin** [ayanamiblhx/nonebot_plugin_setu#24]
新年快乐！
使用时注意到触发指令不需要额外添加前缀，虽然有CD限制，但有时在聊天时会提到关键词
希望增加可选可自定义的命令前缀（或默认使用机器人的命令前缀）
如果已经具备该功能，请告诉我在哪里调试它
感谢！

**Comment by ayanamiblhx** [comment]
> 新年快乐！ 使用时注意到触发指令不需要额外添加前缀，虽然有CD限制，但有时在聊天时会提到关键词 希望增加可选可自定义的命令前缀（或默认使用机器人的命令前缀） 如果已经具备该功能，请告诉我在哪里调试它 感谢！

色图相关命令使用正则表达式触发，command_start无法对其进行限制，要是有相关需求建议直接改源码，具体位置在__init__.py的22行开始
