### ISSUE TITLE
发送色图后报错

### ISSUE THREAD

**Issue by SherkeyXD** [ayanamiblhx/nonebot_plugin_setu#25]
> add_withdraw_job() got an unexpected keyword argument 'forward_id',本次涩图不计入cd

<img width="517" alt="image" src="https://user-images.githubusercontent.com/57581480/218311521-7255231d-c7db-4b80-9300-7bb8a774aafb.png">

**Comment by ayanamiblhx** [comment]
> > add_withdraw_job() got an unexpected keyword argument 'forward_id',本次涩图不计入cd
> 
> <img alt="image" width="517" src="https://user-images.githubusercontent.com/57581480/218311521-7255231d-c7db-4b80-9300-7bb8a774aafb.png">

已修复
