### ISSUE TITLE
魔法

### ISSUE THREAD

**Issue by fireg228** [ayanamiblhx/nonebot_plugin_setu#26]
魔法是啥意思

**Comment by ayanamiblhx** [comment]
> 魔法是啥意思

不知道没关系，关闭魔法就行

**Comment by fireg228** [comment]
大概讲一下呗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ayanamiblhx/nonebot_plugin_setu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ayanamiblhx/nonebot_plugin_setu] 魔法 (Issue #26)





  
魔法是啥意思
  
不知道没关系，关闭魔法就行
