### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by MasterYuan418** [ayanamiblhx/nonebot_plugin_setu#3]
![图片](https://user-images.githubusercontent.com/58651976/135754305-e95692c9-84fb-4ea5-8474-20031a147fce.png)'
出现了`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)`错误。
代理配置有效。

**Comment by MasterYuan418** [comment]
多试几次，就成了：
![图片](https://user-images.githubusercontent.com/58651976/135754345-12cb6e3a-aca1-44bd-a4ee-d95b5daec7f5.png)

**Comment by ayanamiblhx** [comment]
> 多试几次，就成了： ![图片](https://user-images.githubusercontent.com/58651976/135754345-12cb6e3a-aca1-44bd-a4ee-d95b5daec7f5.png)

估计是代理网络不好

**Comment by MasterYuan418** [comment]
@ayanamiblhx 请问能否关闭掉httpx的SSL验证？百度了一下只能查到urllib3的:(

**Comment by ayanamiblhx** [comment]
> @ayanamiblhx 请问能否关闭掉httpx的SSL验证？百度了一下只能查到urllib3的:(

import ssl

ssl._create_default_https_context = ssl._create_unverified_context

**Comment by MasterYuan418** [comment]
@ayanamiblhx 已经尝试过该方案，照样报`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)`

**Comment by ayanamiblhx** [comment]
> @ayanamiblhx 已经尝试过该方案，照样报`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)`

你在哪个文件下加的这条语句？

**Comment by MasterYuan418** [comment]
@ayanamiblhx 在`async def downPic(datas):`之后添加的。
![图片](https://user-images.githubusercontent.com/58651976/135755094-48a695e5-e6f5-4441-b225-4a50dfbb75ec.png)

**Comment by ayanamiblhx** [comment]
> @ayanamiblhx 在`async def downPic(datas):`之后添加的。 ![图片](https://user-images.githubusercontent.com/58651976/135755094-48a695e5-e6f5-4441-b225-4a50dfbb75ec.png)

你把它放在文件开头

**Comment by MasterYuan418** [comment]
@ayanamiblhx 然后又回到了这个熟悉的报错了...是我脸太黑吗
![图片](https://user-images.githubusercontent.com/58651976/135755977-e880bba1-f205-4a54-8edf-3b2f0dbd6678.png)

**Comment by ayanamiblhx** [comment]
> @ayanamiblhx 然后又回到了这个熟悉的报错了...是我脸太黑吗 ![图片](https://user-images.githubusercontent.com/58651976/135755977-e880bba1-f205-4a54-8edf-3b2f0dbd6678.png)

看看.env配置文件

**Comment by MasterYuan418** [comment]
![图片](https://user-images.githubusercontent.com/58651976/135756239-141821b4-4c81-478f-bc2c-6b90fcd7bf22.png)
@ayanamiblhx

**Comment by ayanamiblhx** [comment]
> ![图片](https://user-images.githubusercontent.com/58651976/135756239-141821b4-4c81-478f-bc2c-6b90fcd7bf22.png) @ayanamiblhx

这是最新版的配置，你用的是旧版本还是新版本？

**Comment by MasterYuan418** [comment]
![图片](https://user-images.githubusercontent.com/58651976/135756832-1d3823e1-12fb-4995-9b73-c2325c2c58b0.png)
`NoneBot 2.0.0a16`
`nonebot-plugin-setu 0.0.4`
`nb-cli 0.5.0`

**Comment by ayanamiblhx** [comment]
> ![图片](https://user-images.githubusercontent.com/58651976/135756832-1d3823e1-12fb-4995-9b73-c2325c2c58b0.png) `NoneBot 2.0.0a16` `nonebot-plugin-setu 0.0.4` `nb-cli 0.5.0`

新版是0.0.5，旧版将PROXIES_HTTP替换成LOCAL_PROXY

**Comment by MasterYuan418** [comment]
@ayanamiblhx 非常感谢，问题已解决，麻烦了
