### ISSUE TITLE
纯小白？请问一下大佬这个东西怎么用？

### ISSUE THREAD

**Issue by Toyama-Kasumi** [ayanamiblhx/nonebot_plugin_setu#5]
我是用的limus-bot 一个QQ机器人 我是想限制bot发送图片 就是不要让bot刷屏 给bot冷却时间 他也是以nonebot为原型弄的，请问大佬，可以给个教程吗？

**Comment by ayanamiblhx** [comment]
> 我是用的limus-bot 一个QQ机器人 我是想限制bot发送图片 就是不要让bot刷屏 给bot冷却时间 他也是以nonebot为原型弄的，请问大佬，可以给个教程吗？

请自行查看源码
